### PR TITLE
updates to pass in token

### PR DESCRIPTION
**Pull request by kkarrancsu**

### CODE REVIEW

**Comment by kkarrancsu** [comment]
Simple update to allow easy user interface to update bearer token, now that default tokens are disabled by spacescope

**Review by misilva73 — CHANGES_REQUESTED** [review]
The changes seem fine. However, I think we need to make two aditional changes:
1. Update the package version
2. Update the readme to explain how to run the simulation with a given token and where an user can get a token (maybe link spacescope docs?). This second part is important now that the default tokens no longer work.

Also, I am wondering where we should stop setting `setup_spacescope_obj()` in `data.py` with the default config and instead require the user to do it before running the code.

**Comment by kkarrancsu** [comment]
thx for comments - agree w/ everything & will update accordingly.

**Review by misilva73 — APPROVED** [review]
Looks good. The readme is clear and easy to follow. Great work 👏

**Pull request merged**
